### ISSUE TITLE
Add some routes that return more data

### ISSUE THREAD

**Issue by drhuffman12** [the-benchmarker/web-frameworks#110]
Some web frameworks seem to work better w/ more or less data packet sizes.

Please add some routes that return more data; possibly just plain text. e.g.:

* existing routes [almost no data]
* small routes [e.g.: N bytes]
* medium routes [e.g.: 10 * N bytes]
* large routes [e.g.: 100 * N bytes]

**Comment by waghanza** [comment]
sure, it could be a good idea.

I think we have to discuss about **production-ready** benchmarks -> using a database, caches ...

**Comment by OvermindDL1** [comment]
It shouldn't be a static set of bytes either (else most good frameworks will just kernel-switch the entire memory set to the pipe, which is not really a good test), rather it should duplicate and echo the data passed in or something.

**Comment by greenlaw110** [comment]
@waghanza do we have plan to implement more testing? As the name suggest this is performance benchmakr for web-frameworks, however there are so many places that can be benchmarked for a web-framework, thing like complex routing, database read/write, JSON parsing, complex request with mutliple parameters, post request with form or JSON payload in body etc.

**Comment by waghanza** [comment]
@greenlaw110 #1728 is a better place to discuss about that.

However, I think that harcoding a `sleep` can be useful (for each endpoint). It can mimic database calls (without adding complexity)

**Comment by OvermindDL1** [comment]
Sleep on the other hand will halt the thread while it sleeps, where accessing the database is async, so that's not quite accurate.  Plus the granularity of sleep is ~15ms on average (OS depending) or slightly greater than 1ms on average in high resolution modes, which can also be a good bit slower than accessing a well tuned database.

**Comment by waghanza** [comment]
Sure @OvermindDL1, but what do you propose?

**Comment by OvermindDL1** [comment]
Most frameworks should have some method to async sleep, that is what should be used as it would accurately represent a database transaction.  For those frameworks that don't have an async sleep then normal sleep can be used, of which that would also accurately represent a database transaction since if those frameworks don't have async then they have to halt for the database to respond back anyway.  I'd imagine almost all except the very basic frameworks would have async though.
