### ISSUE TITLE
Introduce gramework

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1135]
+ Language : go
+ Repo : https://github.com/gramework/gramework
+ Author : @kirillDanshin

**Comment by kirillDanshin** [comment]
I don't like the idea to list gramework in a list that maintained by iris author when that benchmark is been used to lie people about performance.

![image](https://user-images.githubusercontent.com/9026581/55109066-fdf5fb80-50e5-11e9-9e88-673bb5f69729.png)

Thanks for your proposal, but sorry, I don't trust gramework's results here even if gramework will be somewhere in the top of the list. I spent a lot of time and money making gramework legal and safe for commercial use, and I've put a lot of work to make gramework stable. I don't want to risk gramework users' trust.

**Comment by waghanza** [comment]
@kirillDanshin You mean that you do not want to list `gramework` here because of @kataras is a **member** of this group ?

I do not have the same opinion, but anyone, I can understand it, and even not understood, I accept your choice

Btw,
+ having any framework here is :heart: 
+ @kataras is a **member**, not a **maintainer** (we are only 3 maintainers, see https://github.com/orgs/the-benchmarker/teams/web-frameworks/members, @waghanza, @tbrand and @aichholzer)
+ there is any open discussion https://github.com/the-benchmarker/web-frameworks/issues/1129 to choose either `iris` **SHOULD** be `here`

**Comment by kirillDanshin** [comment]
@waghanza no. I mean that I don't want to list gramework here because @kataras got a write access here. most of commits here are not signed (a.k.a. Verified), so I don't know what to expect here, keeping in mind multiple git history rewrites, issue editing etc.
I'm sorry I get it wrong and call @kataras a maintainer, I was wrong there.

now, I'm totally with @peterbourgon here (#1138). maybe Peter have another opinion on this situation, but in one thing we're on the same page: we both don't want our work to be in one list with that "fastest community-driven web framework on (THIS) Earth". You may have not know about it, but in the most of Go community comparisons with Iris is already an affront.

---

_/me paying respects to_ @peterbourgon.

**Comment by waghanza** [comment]
@kirillDanshin @kataras does not have write access to this repo ;-)

**Comment by kirillDanshin** [comment]
_waiting for the "edited by kataras"_ 🤣

**Comment by waghanza** [comment]
:stuck_out_tongue: 

PS : I will not add `gramework` unless you allow me to :heart:

**Comment by waghanza** [comment]
Btw, I think having signed commits here, could be a nice feature

**Comment by kirillDanshin** [comment]
well, I'll stick with @peterbourgon. if you'll get his approval on #1138, you can add gramework too.

just ping me to review the PR with gramework then: I just found that someone added an old version of gramework in TFB and used a slow json encoding path for json encoding benchmark O_o

**Comment by waghanza** [comment]
TFB includes alors `iris` 😆

**Comment by kirillDanshin** [comment]
🤷‍♂️no one ask me before adding gramework

**Comment by waghanza** [comment]
It's a shame. We try to do the same as TFB here (but simpler)

**Comment by waghanza** [comment]
Hi @kirillDanshin, `iris` will be removed in #1183 

Do you mind had `gramework` here ?

**Comment by kirillDanshin** [comment]
@waghanza you've got my permission, as long as the list is toxic-free, you know. altho, please ping me before merging the PR so I can review if implementation is ok

**Comment by waghanza** [comment]
Awesome
