### ISSUE TITLE
Introduce integrant

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1393]
+ Language : clojure
+ Repo : https://github.com/weavejester/integrant
+ Author : @weavejester

**Comment by waghanza** [comment]
Hi @weavejester,

Are you OK to include `integrant` in this list ?

Regards,

**Comment by weavejester** [comment]
Integrant isn't a general purpose framework, rather than a web framework. You'd have to combine Integrant with some other combination of libraries in order to get a web application running, in which case I think you'd more be testing whatever additional libraries you chose, rather than Integrant itself.

Duct, on the other hand, is designed for web use, so I'd be fine with that being tested.

**Comment by waghanza** [comment]
Ok. Thanks for this clarification, closing in favor of https://github.com/the-benchmarker/web-frameworks/issues/1374
