### ISSUE TITLE
Add clastic

### ISSUE THREAD

**Issue by ClimenteA** [the-benchmarker/web-frameworks#1823]
+ Language : Python
+ Repo : https://github.com/mahmoud/clastic
+ Author : Mahmoud Hashemi

**Comment by waghanza** [comment]
Hi @mahmoud,

Would you mind to add (or consent that we add) [clastic](https://github.com/mahmoud/clastic) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by ClimenteA** [comment]
Hi, 
I'm not Mahmoud. If I can't submit a framework that I didn't build, please ignore this request.
I found clastic and looks nice, there is not tight coupling between objects.

**Comment by waghanza** [comment]
@ClimenteA thanks for your request, my message (https://github.com/the-benchmarker/web-frameworks/issues/1823#issuecomment-536268295) above was not to ask @mahmoud to work on it.

However, since I have some troubles in the past (https://github.com/the-benchmarker/web-frameworks/issues/1129) I prefer to ask for consent before adding any framework. Just after @mahmoud give his consent, I'll be glad to review any `PR` (from you or anyone else) :heart:

**Comment by mahmoud** [comment]
Hey hey! This is exciting. clastic wasn't really built for performance per se, but we did use it in performance-critical use cases at PayPal. So, have fun, I say.

Note that for routes as simple as these, I'm fairly certain that the WSGI container/server is going to dominate. If we find otherwise, that's a bug I'll fix :)  Looks like gunicorn/meinheld is the setup for the flask case, and the same should work for clastic.

Happy for someone else to do the work, otherwise I may have some time in the next couple months. Just let me know. Thanks!
