### ISSUE TITLE
Select architecture to run

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2011]
Hi,

Results could have a huge variation. For example, when I use an AMD FX-8320 (4 CPU / 8 Gig) I have following results => https://github.com/the-benchmarker/web-frameworks/blob/0afe603a74a87522ba5a0164825ec38e7f583f80/README.md#results.

However, using a Core i7 i7-8850H (12 CPU / 16 Gig), I have https://github.com/the-benchmarker/web-frameworks/blob/d2d8553f58b66913b7116554c5d3e6ef79836e60/README.md#results 

Any ideas @the-benchmarker/web-frameworks of any size to use ?

Regards,

**Comment by doanguyen** [comment]
After skimming the results I think it looks consistent somehow. However, it is still bugging me because of abnormal throughput/reqs ratio for several PHP frameworks. It reminds me of https://github.com/the-benchmarker/web-frameworks/issues/421

## first scenario

![Imgur](https://i.imgur.com/5qcIiMD.png)

----
## second scenario

![Imgur](https://i.imgur.com/IAtHB7y.png)

**Comment by waghanza** [comment]
what are you first and second scenario ?

**Comment by doanguyen** [comment]
First is the first computer (with AMD) and second is the one with i7 processor.

To me both results are somewhat similar

**Comment by waghanza** [comment]
ah, ok. in term of `req/s`, but their are completely different in term of **latency**

**Comment by doanguyen** [comment]
I'm not sure the latency and `throughput/reqs` are relevant?

isn't this ratio must be more or less be equal in any benchmark?

**Comment by waghanza** [comment]
no, it depends on the **framework** tested (async / sync, WSGI, ASGI ...) 

it is an other indicator, as `req/s` is

**Comment by doanguyen** [comment]
I mean the ratio `throughput / reqs/s` not the `throughput` itself. 

I guess the request return in bytes of each request are almost the same, so multiple with req/s should results in corresponding throughput (I means the `throughput/reqs` ratio must approximately equal, the different might have because of the different in headers size).

Also because I've never got > 10k req/s with laravel on my machine (i7 4 cores 16G). But may be I got things wrong in my setup.

I'm trying to check some php frameworks, is this just a normal Dockerfile or do I need to do something else?

**Comment by doanguyen** [comment]
Hi again,

I've just rebuild the docker image, everything worked perfectly but I have difficulty to get to 36k req/s with laravel (first scenario let alone 86k req/s in the last case).

The high throughput from laravel might come from its heavy session_id, so it could explain somehow.

Otherwise, I think the choose of the machine is up to you.

**Comment by waghanza** [comment]
@doanguyen I think I will use https://www.packet.com, powered by `kubernetes` (or any `docker` orchestrator) in the first time

But I need a lot of time to create tools for ... It could be long
