### ISSUE TITLE
results table

### ISSUE THREAD

**Issue by stakach** [the-benchmarker/web-frameworks#2029]
The response time metric in the table doesn't seem to be accurate so the table should probably be sorted by requests per-second, as that is the most telling measurement.

There are three metrics that need to be taken into account:

* Speed (how fast is a single request after warm-up without any other factors)
* Parallelism (does the service scale horizontally)
* Concurrency (does the service scale vertically)

So if you are throwing requests at a service to see how fast it is under load then response time should be:
`1.second / requests_per_second`

However it looks like the response time is measured from after the socket is negotiated to response returned which punishes concurrency.
So a fast, single threaded server with no concurrency does better than a fast, parallel and concurrent server or a fast concurrent server (a fast parallel server should be equal)

<img width="862" alt="image" src="https://user-images.githubusercontent.com/368013/70106501-ee2caf00-1697-11ea-85a0-4cff1fb7248d.png">
So the table is then hard to read and the ordering meaningless.

I think most people are interested in request-per-second which shows the frameworks that are most capable at all of the metrics above.

**Comment by waghanza** [comment]
I am totally up with you @stakach 

However, the table here **is** and **will be** hard to read.

I explain myself a bit, depending on you reading (and your needs) table could be hard to read, that's why we have started https://github.com/the-benchmarker/frontend (tanks to @doanguyen) to display the results.

Having a static table could be readable for one aspect (not very accurate for now, also due to the way of computation). I'm open to any suggestion about sorting or else (at least what could be done quickly ^^)

wdyt @the-benchmarker/web-frameworks  ?

**Comment by mdagit** [comment]
Take a look at https://github.com/giltene/wrk2 as an alternative to wrk as it does a better job at keeping a desired request rate versus just keeping pace with the target server with just a few threads, which is totally unrealistic.

Another choice is the ancient https://acme.com/software/http_load/ which still does a more realistic job than many more recent load testing tools.

In other words, instead of just serially sending requests and measuring the cooperative response rate, better would be to do a fixed load (say at 10k/sec, 50k/sec, 100k/sec, 500k/sec, etc., depending on the hardware and network) and report on latency statistics and errors.

**Comment by waghanza** [comment]
Hi @mdagit,

Totally up with this. 

However, their is some other stuff to do before.

Take a look at https://github.com/the-benchmarker/web-frameworks/issues/1618.

After the first task complete, the results will be completely different since a **real** network will be tested, instead of a local loop-back as for now.

However, I'm not sure using an other sieger will increase result accuracy. For example, https://github.com/TechEmpower/FrameworkBenchmarks use `wrk` and results seems to reflect a reality.

Regards,

**Comment by mdagit** [comment]
All benchmarks reflect "a reality" :) ...
it just might not be relevant for most people, and it might not actually be measuring what most people think it is.
Generating 100k requests sequentially on a few client threads is *very* different in effect on a server from 100k requests 
timed randomly among 10k independent threads (or entities logically equivalent to a thread, using an event-based client).

By Little's Law, with some small print:
 concurrency [aka "occupancy'] = latency x throughput
Different load test tools are designed to hold one of these constant and experimentally measure the others.
However, the better tools generally do this in such a way that the arrival timing is close to Poisson.
Timing from a single real world client is not Poisson for a bunch of reasons (browser logic for dependent assets;
use of pipelining and/or HTTP/2, etc).
But timing *across* real world clients is of course uncorrelated.

-mda

**Comment by waghanza** [comment]
@stakach As I understand [your comment](https://github.com/the-benchmarker/web-frameworks/issues/2029#issue-532403771), their is 2 things :
+ Table is too dense (too much details)
+ The response time is not measured in a good way, because it is measured from after the socket is negotiated to response returned which punishes concurrency.

For the first point, I propose to display only `request/second`, but with a table header labeled as **Speed**, the only stable metric mesured here.

After running on a good infrastructure, I'll add `Parallelism` and `Concurrency`

For the second point, the response time is mesured by `wrk`, as https://github.com/TechEmpower/FrameworkBenchmarks does

Any tool is ok for me

At least the purpose of this benchmark is more to be a promotion of OSS and awesome work any tech does :heart:

**Comment by stakach** [comment]
I think the speed header makes the most sense

**Comment by waghanza** [comment]
I will ping you on my `PR` to change table

**Comment by stakach** [comment]
Was thinking that, with the table as it is displayed now, there are only two easy measurements:

* Overall Speed (request / s)
* Response time average (measuring socket accepted -> response)

i.e you should roughly find that
`(overall speed * response time) == 1 second` for a single threaded non-concurrent server
`(overall speed * response time) == num_threads seconds` for a parallel server
`(overall speed * response time) > num_threads seconds` for a parallel concurrent server

But not sure how you can really determine if a server is parallel or concurrent unless you can guarantee that a parallel server is only using X threads in its thread pool.

For instance, Ruby apps probably use multiple processes but each of those processes will spawn multiple threads except there is a lock so there isn't much overlap in the threads, but there will be some.
