### ISSUE TITLE
why doesn't exist  Rocket.rs !!??

### ISSUE THREAD

**Issue by javidoweb** [the-benchmarker/web-frameworks#2057]
+ Language : Rust
+ Repo : https://github.com/SergioBenitez/Rocket
+ Author : SergioBenitez

**Comment by waghanza** [comment]
Hi @javidoweb,

`Rocket` has been remove (temporarily) from this list since https://github.com/SergioBenitez/Rocket/issues/19.

After the above issue will be closed, I'll add `rocket` here.

The main idea, is to use **stable** version of each languages, frameworks ...

Regardes,

**Comment by apiraino** [comment]
hello @waghanza 

I respectully disagree with removing / ignoring `rocket.rs` until it's "stable".

In the Rust world, web frameworks move fast, so "stable" has (for now) a slightly different connotation than in other programming languages. I agree with you that running on Rust stable is absolutely desirable and it's a great "selling point", but on the other I would not find fair to hide one of the most "stable" and maintained web frameworks in the Rust ecosystem.

I don't have official figures about usage, but Rocket is always mentioned when asking about Rust web frameworks (anecdotally, I use it, too).

Anyway, this repo is yours, so decision is of course up to you, just wanted to share my .2 cents :)

cheers,

**Comment by poszu** [comment]
I'd love to see Rocket.rs here too. Perhaps some label saying "it's using unstable" next to the result would be a good compromise?

**Comment by OvermindDL1** [comment]
Rocket.rs is not unstable, it's just using nightly rust, and it only uses nightly rust because it depends on a single proc-macro related feature in nightly rust that is coming to stable quite soon now, so even that won't be an issue soon.

However, Rocket.rs is updating to async processing in the next major version, which will be soon after rust releases that new feature on stable.  It would be interesting to see rocket.rs in now, then update it when it updates to see how the performance changes then.

**Comment by apiraino** [comment]
https://github.com/SergioBenitez/Rocket/issues/19#issuecomment-630650328

**Comment by EvanCarroll** [comment]
@javidoweb can this issue be reopened, re: https://github.com/the-benchmarker/web-frameworks/issues/2057#issuecomment-631507218

**Comment by waghanza** [comment]
@javidoweb @OvermindDL1 @EvanCarroll @apiraino @poszu `rocket` could be re-introduced ♥️
