### ISSUE TITLE
uWebSocket supicious ?

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2143]
Hi @Fenny,

You inform me that the is some stories about `uWebSocket` 
@see https://medium.com/@rockstudillo/beware-of-uwebsockets-js-b51c92cac83f 

Thanks for notification :stuck_out_tongue: 

/cc @alexhultman @dalisoft @aadityataparia @jkyberneees 

---------------

The idea `here` is to determine if `uWebSocket` based frameworks could be listed `here`

---------------

Personally, I have no idea of how `npm` **registry** works

**Comment by dalisoft** [comment]
It’s interesting. I didn’t noticed any mining or something similar yet. 
Let’s waiting answer from @alexhultman

**Comment by Fenny** [comment]
The project is also sponsored by some shady crypto companies that have a bad record.
There is a reddit thread somewhere regarding all these issues, cant seem to find it atm.

**Comment by alexhultman** [comment]
Don't ping me to talk behind my back.

That link you posted already has an answer, if you cared enough to read your own nonsense.

https://link.medium.com/HNjrZBlid3

I don't care about any of you, or what you do, I'm not doing anything for you and I am in no way in your debt. Nobody is twisting your arm or force feeding you anything.

Fuck off and go do whatever you want, I literally do not care the slightest what you may or may not, as long as you don't infringe on my intellectual rights.

Sincerest

**Comment by waghanza** [comment]
Sorry @alexhultman that this subject bother you.

The intention is not to hurt you or anything, but hear about you around this. It could be a safety issue, not only for `uWebSocket.js`, but with any library using it.

Also I'm not sure using injure helps in any way `here`.

The code of conduct https://github.com/the-benchmarker/web-frameworks/blob/master/CODE_OF_CONDUCT.md does not allow injure at all

Please change you language / behavior in face of this community.

**Comment by alexhultman** [comment]
> The project is also sponsored by some shady crypto companies that have a bad record.
> There is a reddit thread somewhere regarding all these issues, cant seem to find it atm.

This is not constructive feedback, it is retold speculations borderline defamation. You could very well be sued from such nonsensical allegations.

You're not my customer, you mean literally nothing to me and I'm in no way liable, in debt or owing you anything, not an answer, not my time, not anything. You're useless to me.

**Comment by waghanza** [comment]
You are right @alexhultman, we are not any of your customer, but that does not mean you can not be polite.

As anyone `here`, you are doing **opensource** stuff, so you take some of your time to provide a solution to a problem. We are aware that is a time (and probably money) investment.

The subject  `here` is not to be against you or what you are trying to achieve, but having some information to determine,, not your honesty, but **safety** of any library that use `uWebSocket`

**Comment by alexhultman** [comment]
If you want to base suspicion on the basis of some grumpy asshole using speculation and tin-foil-hat conspiracy theories, I don't care. I have no time to individually persuade non-paying conspiracy theorists. You really don't get it - I don't honestly **care** what you think.

You don't think I have heard it all by now? You're not exactly the first to raise this question, I've heard it since 2016.

**Comment by waghanza** [comment]
@alexhultman Please be polite. Even you disagree with some people (and I understand how boring could be the context) you have **NOT** to injure them 
the same is for you @Fenny -> if you have any facts to give us please be my guest

as far as I've read issues, posts ... 2 things are coming to me :
+ an issue has been deleted on `uWebSocket.js` repo, and I think this is not fair
+ the builds are made by `AppVeyor`/`Travis`. despite any idea I have about that, I don't find how this could be any security issue

for me @dalisoft and @aadityataparia libraries has their places `here`, and even you @alexhultman, their is not **facts** to give any reasonable argumentation about security failure `here`

I wish therefor to let this issue open as a debate, and even their is some conclusion, I'm not OK with I'll apply them

/cc @the-benchmarker/web-frameworks

**Comment by alexhultman** [comment]
> their is not facts to give any reasonable argumentation about security failure here

Right, it's just speculations made by one guy and nobody knows who he is or what he does.

I even remember he wrote me about a feature and when I didn't prioritize his wish, this medium post was written in some kind of childish retaliation.

Incredible how little people really care to check facts nowadays. It's just retold sensationalism based on rumors by some unknown dude.

"The Earth is flat", people say, yet they use satellites and iPhone to convey it, how utterly ironic.

**Comment by dalisoft** [comment]
I too got two sponsor (one sponsored me by hiring me) and one give me some money. I don't know them.
I think uWebSockets.js sponsors pays only for high-performance backend server, not for any bad things, @Fenny do you think about this?
From sponsoring both sides get benefits (author of library gets more motivated) and sponsor can get features they want. I don't care about this as i'm no sponsor, just one of user of uWebSockets.js.

@waghanza For me important is SECURITY, about `npm` version or other things i don't care, because these are happened in past. I just want to be sure it's really SECURE? (not mining or something) As 2K (monthly 2K nanoexpress downloads) users using my library on top of uWebSockets.js and they happy.

We all people, let's close discussion for me one word, YES or NO.

@alexhultman I even don't know how hard is make high-performance library/framework, because uWebSockets.js a lot of faster than any of libraries even i made for backend (including private servers), can you confirm uWebSockets.js is SAFE to USE? I think yes, but confirmation from author is better

@Fenny if you have any facts, please share with us, if it's just hype for disinformation peoples, please apologize from @alexhultman and @waghanza

I am didn't noticed any security issues yet.

Who isn't agree with me, you can DISLIKE my comment

_Sorry for bad english if there any mistakes, i hope you're understand_

**Comment by doanguyen** [comment]
> The idea here is to determine if uWebSocket based frameworks could be listed here

I think the arguments worked on both sides, the author has his method to solve the problem (via using the mutable versioning), however, the method is not backed by any community because of the security risk. Even though the javascript library is deprecated so we could not see the log, I think we should not include the newer version of the javascript library to our benchmark.

On the other side, the C++ library is not a subject of the discussion and it has no problem with the building, packaging and distributing. I think if it possible then we can include it (https://github.com/uNetworking/uWebSockets)

**Comment by waghanza** [comment]
@dalisoft The fact is their is two things : **history** and **security** (and of course one could depend on the other).

1. History => For me not any problem with the library
2. Security => For me not any problem with the library

We can end / close this debate like https://github.com/the-benchmarker/web-frameworks/issues/1129#issuecomment-477328645, I remember at the time (but I  `golang` **communities**) I had to remove `iris` and `muxie` here, because of security issues :heart: 

@the-benchmarker/web-frameworks Please vote / react, and I'll remove / keep iris here

Voting stop on 30th of january 2020

Please add a +1 for keeping, and -1 for removal

**Comment by alexhultman** [comment]
> can you confirm uWebSockets.js is SAFE to USE?

Holy shit what don't you understand? I have thousands of users, millions of end users, billions of USD in transit and contracts with companies here and there what is wrong with you? I don't need to answer that question, I've been doing this shit for 4 years and you side with some random speculative nobody. Do you understand that I would be sued to the end of the world if I did anything like that?

**Comment by waghanza** [comment]
@alexhultman please calm down, this is no helping, thus

**Comment by dalisoft** [comment]
@alexhultman Sorry, i'm not from any side, i'm just asked. I care about 2K users of my library.

**Comment by alexhultman** [comment]
You're missing my point; I don't care what you do. Like I said I develop things commercially, meaning I take money and give features. That's capitalism. I only care for capitalism and the contracts I sign and the indemnification I sign. What you do here is irrelevant to me. But you shouldn't assume things you have no facts about. But again, I really can't care less.

**Comment by waghanza** [comment]
@alexhultman this issue is more about safety for **this** project, now that we have red your arguments, we can decide, as a **community**

**Comment by alexhultman** [comment]
> the author has his method to solve the problem (via using the mutable versioning), however, the method is not backed by any community because of the security risk.

I've never argued for mutable versions. That's a retold misconception.

I'm arguing for owning and controlling ones intellectual property, including the right to delete versions, such as in legal disputes.

Nobody is arguing about changing released versions and in fact nobody **can** because you have Sha1 hashed tags in Git.

It's really making a hen out of a feather all of this; you argue about things you can easily control.

1. Nobody is forcing you to use the binaries
2. Nobody can edit, remove or alter any Git commit since there are like a thousand forks and you easily can add your own by clicking the mouse "Fork" like how lazy and demanding can people be? You expect me to massage your customers for you as well?

**Comment by doanguyen** [comment]
> @alexhultman Sorry, i'm not from any side, i'm just asked. I care about 2K users of my library.

He was quite clear that he does not care about that, including your 2K users now or later on. The thing is that if you use other famous libraries, such as React, Angular,... they also do not care about your users. The different is that they (react, angular...) had transparent records (or at least they tried) to make sure they do not (or will not) fuck you up now/later on.

Personally, I don't support these behaviours (from the author) even though he is a great programmer (this I don't know), and I think we should not go on with this javascript library. But this is my opinion only.

**Comment by dalisoft** [comment]
I keep using uWebSockets.js as core for my own library. Implementing adapter to switch is not a bad idea at all, but there i didn't found any alternative with same performance and adopted to Node.js

**Comment by waghanza** [comment]
@dalisoft depending on the result of https://github.com/the-benchmarker/web-frameworks/issues/2143#issuecomment-573656160, but in my opinion there is not **real** reasons to do so :stuck_out_tongue:

**Comment by Fenny** [comment]
@alexhultman, why did you delete all your comments?

**Comment by vmark2020** [comment]
Off-topic, if uWebSocket based frameworks were removed from the list, the author of the affected frameworks planning to switch to next language e.g. Go (since fasthttp is the highest and battle-tested)? 

Feel free to downvote or remove if it's not a useful question to this issue.

**Comment by waghanza** [comment]
@vmark2020 This is clearly off-topic comments. The decision to switch or not to switch are up-to author and have more consequences from only performances

**Comment by waghanza** [comment]
any thoughts @vladfaust @ohler55 @OvermindDL1

**Comment by ohler55** [comment]
Whether dangerous or not I can't say but it does bring into question why releases can't be immutable like all other packages. I'd hate to exclude frameworks but if you can't count on a release being the same when you try it at home the benchmarks are meaningless. Fortunately, if getting a release from npm it should be immutable so that seems safe enough unless I am missing something.

**Comment by OvermindDL1** [comment]
Hmm, after a quick skim-reading the article and skim-reading the comments here a couple things:

### Related to this project:

* That seems more of a framework for websockets rather than web serving, so I'm not sure it has a reason to be here unless websockets are starting to be benchmarked?

### Unrelated to this project

<details>
<summary>Ignore this section if you are not interested in personal remarks</summary>
* What on earth, someone against immutable releases?!  That is an exceptionally questionable stance considering what's happened in the past.  I don't see how anyone could possible hold such an opinion after knowing about the history of mutable releases...  o.O
* Personally the author appears to have some public interaction issues; from a quick reading of his various content posted online I'm guessing some form of social interaction disorder (narcissism, autism, etc...) and no one has managed to have him actually explain his stance in a way that shows that he understands the results of his actions on others in anything less than a surface way.
</details>

### Suggestion

I'd vote to remove this on the grounds that it doesn't seem to be the right kind of thing being tested for a web framework as it's geared toward specifically websockets.

**Comment by ohler55** [comment]
I might have been confused as to the features of the uWebSocket. I made the assumption that it was in some part of web server as well as just a plug-in for Websockets. If that is not the case then I completely agree with @OvermindDL1, including there "unrelated" comments.

**Comment by OvermindDL1** [comment]
It 'is' a web server in so much you have to handle the HTTP packet protocol to be able to set up a websocket connection, and thus consequently it has the basics needed for web serving.  Beyond that it doesn't handle the full HTTP spec properly from what I read, has no advanced dispatching mechanisms, etc...  You 'can' do http with it, but that is very obviously not what it's designed for, it's designed for websocket work.

**Comment by dalisoft** [comment]
@OvermindDL1 It's great if there any alternative to uWebSockets.js, but theres no ones can provide add-on for Node.js. I love to see if there will be any alternative and can help from Node.js side. I cannot able to create add-on even for agoo-c by @ohler55 
For Node.js developers only uWebSockets.js can provide high performance.
Maybe i'm wrong

**Comment by waghanza** [comment]
@OvermindDL1 you're right. this tool seems named to be more for **websocket** things, but you can do exactly what we need `here` :stuck_out_tongue: 

@dalisoft https://www.npmjs.com/package/ws is not suitable ?

@OvermindDL1 @ohler55 please vote on comment https://github.com/the-benchmarker/web-frameworks/issues/2143#issuecomment-573656160, it will be easier for me to decide of remove or else ...

**Comment by dalisoft** [comment]
@waghanza ws only for Websocket, i really love that library. Works fine everywhere i used. If ws could handle http requests, i can migrate

**Comment by aadityataparia** [comment]
FYI: I will not migrate.

Feel free to remove `sifrr` if it is the consensus.

Also, I don't think there is any reason to remove it, as far as I understand this repo provides benchmarking and in no way endorses any frameworks listed here and users are free to choose framework they want taking other things in consideration. So it should be upto user to decide if any framework/library listed here is safe for them to use or not. And there seems to be no `Contributing` guideline that enforces the criteria of security/past problesm/ not listed on npm, etc for frameworks to be added in this repo.
If you decide to remove this library, please add/update guideline with criteria needed to be listed.

**Comment by waghanza** [comment]
@aadityataparia I'm not sure this has to be in any `Contributing` guidelines, as any security issue **COULD** happen after introduction (_guidelines_ do not help avoiding that).

The main goal of this project, is to help to take decision (by having real metrics). It's then our value (as a **community**) to enforce trust in any software part `here`.

The purpose of this thread is to decide whether the **frameworks** in which `uWebSocket` is part of, could be safe, nothing more

I'm not sure to make this in any `guidelines` but clarification in documentation could help.

Btw, thanks for the idea :heart:

**Comment by inlet3355** [comment]
I can see the vote outcome is even unless waghanza's vote should not be counted.

**Comment by waghanza** [comment]
@inlet3355 why my vote should not count ?

**Comment by inlet3355** [comment]
You have previously allow uWebsocket framework to be used in this benchmark as it's interesting in this project, now you shouldn't take sides, it should be fair to let the community and others' votes be the decision maker.

Rather, only framework authors are eligible to vote in this case.

**Comment by ohler55** [comment]
It is @waghanza repo though. In the end he decides the rules. I think this is getting too involved and too complex. @waghanza, you have the inputs, make a decision and move on.

**Comment by waghanza** [comment]
@inlet3355 any member can vote :stuck_out_tongue: 

@ohler55 you're right, I have to decide. I have not precise any `timezone`, so I'd prefer to let time past.

Now I can take a decision, as there is 4 vs 4 is https://github.com/the-benchmarker/web-frameworks/issues/2143#issuecomment-573656160, there is no reason to remove **uWebSocket** based `frameworks` from `here`
