### ISSUE TITLE
Strange results in plezi, and sometimes failing

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2165]
Hi @boazsegev,

I have some strange results for `plezi`.

I'm using `wrk` to get statistical results, `req/s` ... and I have :

+ `wrk -H 'Connection: keep-alive' --latency -d 15s -c 1000 --timeout 8 -t 16 http://172.17.0.4:3000/`
```
Running 15s test @ http://172.17.0.4:3000/
  16 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   164.09ms  227.79ms   1.47s    83.53%
    Req/Sec   232.27    558.20     4.25k    92.19%
  Latency Distribution
     50%   24.55ms
     75%  276.82ms
     90%  516.83ms
     99%  894.23ms
  28164 requests in 15.09s, 0.00B read
  Socket errors: connect 992, read 28164, write 0, timeout 0
Requests/sec:   1866.45
Transfer/sec:       0.00B
```
+ `wrk -H 'Connection: keep-alive' --latency -d 15s -c 1000 --timeout 8 -t 16 http://172.17.0.4:3000/user/0`
```
Running 15s test @ http://172.17.0.4:3000/user/0
  16 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    15.18ms    4.53ms  69.00ms   73.04%
    Req/Sec     4.04k   464.17    12.90k    86.09%
  Latency Distribution
     50%   13.99ms
     75%   17.52ms
     90%   21.70ms
     99%   28.86ms
  965903 requests in 15.09s, 130.80MB read
Requests/sec:  64014.21
Transfer/sec:      8.67MB
```
+ `wrk -H 'Connection: keep-alive' --latency -d 15s -c 1000 --timeout 8 -t 16 http://172.17.0.4:3000/user` (**POST** via `lua`)
```
Running 15s test @ http://172.17.0.4:3000/user
  16 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    82.58ms   74.17ms 240.63ms   56.25%
    Req/Sec    26.20     17.39    56.00     80.00%
  Latency Distribution
     50%   60.07ms
     75%  150.47ms
     90%  191.63ms
     99%  240.63ms
  64 requests in 15.09s, 0.00B read
  Socket errors: connect 992, read 64, write 0, timeout 0
Requests/sec:      4.24
Transfer/sec:       0.00B
```

Regards,

:warning: I'm on the same machine, perhaps it's a problem

**Comment by boazsegev** [comment]
@waghanza ,

Hmm... **Sidenote**: `keep-alive` is `wrk`'s default mode. No need to manually specify the header.

I think I would need more information to help with that.

`wrk` has a known issue where sometimes `connection` errors appear ass `read` errors (due to the fact that the connection establishment state is unblocking.

A lower number of errors, especially on the same machine, might indicate the (listening) socket's backlog is full and a connection establishment failed (and later reattempted). However, the large number indicates a different error must have been occurring.

If these `read` errors actually relate to connection errors, there's a chance that you might be running out of socket addresses while repeating the statistical tests.

Each TCP/IP address (even on the same machine) remains "busy" for 2 minutes after the connection was closed. This is an OS requirement. The 2 minutes are used to make sure that all the "echos" cause by network routing "die out" before an address could be recycled.

There's a limited amount of available addresses since the addresses are made of an address:port touplet and you are using them very fast since you only have a single IP address (on a single machine, used by both client and server)...

Just a theory, I have no real idea what's the error. It would be nice if you could provide more information to track down the issue.

**Comment by waghanza** [comment]
@boazsegev Thanks for the clarification. What kind of information do you need to track down this issue ?

**Comment by waghanza** [comment]
@boazsegev Using a `5 seconds` tests with `8` treads on a concurrency of `800`, everything is find. I think I'll use those params since we are still in **development**.

However, we have to change those for **production**

**Comment by boazsegev** [comment]
@waghanza ,

The information I need will be the information that will allow me to reproduce the issue.

Server startup logs and error logs might be nice as well.

Which OS are you running? Docker file? Open file limit (`ulimit`)? Server settings (iodine workers & threads)?

I would also need example code that replicates the issue, since it could be anything right now (it might be an issue with the database connection pool, who knows)...

Thanks.
