### ISSUE TITLE
[Go] FastHTTP Prefork version

### ISSUE THREAD

**Issue by infeno** [the-benchmarker/web-frameworks#2268]
+ Language : Go
+ Repo : https://github.com/valyala/fasthttp/tree/master/prefork
+ Author : @savsgio

Prefork version has been merged and should see performance gains, I think the current code in this benchmark repo does not use prefork. Assuming, it will be on the same range as sifrr and nanoexpress. If that blazing fast, it is worth adoption although, I understood we need real world scenario that is on-going. Great work for the authors and @waghanza !

**Comment by waghanza** [comment]
Thanks for your kind words @infeno :tada: 

Indeed `fasthttp` do not use **prefork**

https://github.com/the-benchmarker/web-frameworks/blob/720c83a4290ab6a616b5698d8d9ade25bd7fe1d6/go/fasthttp/main.go#L18-L40

but `fiber` use it

https://github.com/the-benchmarker/web-frameworks/blob/720c83a4290ab6a616b5698d8d9ade25bd7fe1d6/go/fiber/main.go#L9

It could be unfair. To be `honest` if it is a thing that usual in **production-grade** application, feel free to use `Prefork` on all `go` **frameworks** that use `fasthttp` instead of `net/http`

Regards,

**Comment by savsgio** [comment]
If you want to use prefork in fasthttp, you must wrap the server with prefork and run it.

https://github.com/valyala/fasthttp/blob/master/prefork/README.md

**Comment by savsgio** [comment]
Fiber include the similar code into the framework to make it easy to use preforks with a simple option in configuration.

**Comment by savsgio** [comment]
The next fasthttp release includes prefork package and i/you could add it to fasthttp in this benchmark

**Comment by waghanza** [comment]
I'll be glad @savsgio :heart:

**Comment by infeno** [comment]
I'm just curious for early evaluation, any speed up with Go 1.1.4rc1? I found page allocator significant speed up for some benchmark I've test.

**Comment by waghanza** [comment]
@inferno I'll not merge rc in **master**, but if you want to get a try :+1: 
+ Clone this repo
+ Change `go/Dockerfile`
+ Run 
```sh
shards install
shards build
bin/make config
bin/neph go --seq
bin/db to_readme
```
+ Enjoy :stuck_out_tongue: 

I can display results on this issue, when I'd be facing a computer :heart:

**Comment by waghanza** [comment]
@infeno I about 10 hours, the results will be updated with `go` **1.14**

@savsgio Fell free to update `go` **frameworks** base on `fasthttp`

**Comment by waghanza** [comment]
@infeno https://github.com/the-benchmarker/web-frameworks/tree/push_docker_registry#results

**Comment by savsgio** [comment]
> /cc @savsgio Any time to make uniform all `go` **frameworks** that use `fasthttp` ?

Done! 😉
