### ISSUE TITLE
Home page test

### ISSUE THREAD

**Issue by proyb6** [the-benchmarker/web-frameworks#2842]
Mentioning about static HTML files benchmark, they are serve 100% of the time and has larger contents size. Does it makes sense to consider this scenario to determine how well the each web framework can perform without front end web server?

**Comment by waghanza** [comment]
I understand what you are saying @proyb6. You mean that the scenario is too simple to represent a majority of use cases.

I agree with you. However :
+ the scenario will evolve (https://github.com/the-benchmarker/web-frameworks/issues/1728) but I want to be very sure, since the development is huge for this task
+ This project is more suited for what so called `backend` (API, proxy, reversee proxy ...)
+ I plan also to have a `full-stack` scenario (not mine obviously but https://realworld.io)
+ A separated repo will be create for `frontend` (I mean to reflect `frontend` use cases)

The main aspect `here` (without taking in count the very long term objectives) is development cost, I mean, I'm the only one leading this project, and hopefully some amazing techies help a lot https://github.com/the-benchmarker/web-frameworks/graphs/contributors

**Comment by proyb6** [comment]
I understand and my opinions:

I don't find realworld.io interesting that `full-stack` could be confusing among authors if they are not well-versed in it. There is a good time to discuss further as you have suggest for a separate repo.
