### ISSUE TITLE
[Java] Add vaadin

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2871]
Hi @Artur- @mstahv @Legioth ,

Would you mind to add (or consent that we add) [vaadin](https://github.com/vaadin/framework) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by Legioth** [comment]
I don't see how Vaadin would be appropriate since it doesn't work on the abstraction level described here.

Vaadin is a UI framework that abstracts away low-level concerns such as client-server communication. It is not a REST framework or even a request/response framework. There are two ways of building UIs with Vaadin: UI logic implemented in Java running on the server or UI logic implemented in TypeScript running on the browser with data access implemented in server-side Java.

The Java-only approach is quite close to typical server-side rendering, except that incremental updates are automatically "rendered" on the server and applied in the browser similarly to how single-page applications work. This means that there aren't any dedicated data endpoints, but instead the application data is embedded inside the UI events and rendering instructions that are sent over the network.

The TS + Java approach has data endpoints, but not in a way that follows the format described in this ticket. Vaadin uses a code-first [BFF](https://samnewman.io/patterns/architectural/bff/) approach that generates a TypeScript client based metadata extracted from the Java counterpart. The wire format is REST-ish, but the abstraction level is on the level of doing RPC rather than REST semantics such as URL structure or HTTP verbs (e.g. GET or POST). There are plans to give the developer more control over such details for cases when they want to be compatible with existing REST APIs, but that capability is not yet at the of the backlog.

**Comment by waghanza** [comment]
Thanks @Legioth for this clarification. 

It appears that I was mistaken reading the documentation (too quick, tbh), `vaadin` use `spring-boot` to provide client-server communication.

`

**Comment by Legioth** [comment]
No worries. Parts of Spring are indeed used as more or less internal helpers for general concerns related to communication, but the user-facing API isn't based on the generic mechanisms offered by e.g. Spring MVC or Spring WebFlux.
