### ISSUE TITLE
[Rust] Add Rocket

### ISSUE THREAD

**Issue by heniotierra** [the-benchmarker/web-frameworks#3137]
Would you add the Rocket REST API framework, written in rust?

**Comment by waghanza** [comment]
Yeah, sûre `rocket` was retired https://github.com/the-benchmarker/web-frameworks/issues/1749, but we will be able to re-introduce it in 3 days (next `rust`)

**Comment by waghanza** [comment]
Hi @SergioBenitez @jebrosen,

Would you mind to add (or consent that we add) [rocket](https://github.com/SergioBenitez/Rocket) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by jebrosen** [comment]
As far as consent, I am not going to tell anyone that they should or should not perform or use benchmarks in general. I do advise against taking benchmarks too much to heart, as it's very easy to accidentally compare the wrong things or to be misled because a benchmark doesn't reflect a specific application's workload - and it's not nearly so easy to tell when that is happening.

---

It seems Rocket was originally removed due to the nightly requirement. If you were to add a rocket benchmark today, you would have to choose between 0.4 (synchronous, nightly) or the `master` branch (async, stable). From that standpoint, it seems to me like waiting for the 0.5 release would be your best option, otherwise you would either have to keep up with nightly rust or with commits to Rocket's `master` branch.

**Comment by waghanza** [comment]
Thanks for your advices @jebrosen. Indeed the hard thing, is this kind of project, is to avoid :
+ avoid an apple-to-orange comparison
+ using this results to explain everything, benchmark are specific to use case, and results could be misleading if misunderstood

but we are trying to keep it as simple as possible and as easy to understand as possible

------
We will wait for 0.5
