### ISSUE TITLE
[PHP] Add Fatfree framework

### ISSUE THREAD

**Issue by loulou2852** [the-benchmarker/web-frameworks#3438]
Hey,

Is it possible to add this framework?

https://fatfreeframework.com/3.7/home

Thanks

**Comment by waghanza** [comment]
It will be awesome. If you mind `PR` ...

------------
This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

------------
We try to keep the implementation simple (and target a **production grade** code)

**Comment by loulou2852** [comment]
Thanks for that, do you have any extensions availabe for PHP like Redis / APCU/ Memcache activated for your tests?

**Comment by waghanza** [comment]
nope. the idea is to keep this as simple as possible, since adding extension could lead to unfair comparison (between languages ...)

however, I'll not merge until @bcosca has given his consent explicitly.

------------
PS : About consent, we also consider it as explicitly given if no answer is given in 10 days (we will document this process when the first non-beta version will be released)

**Comment by waghanza** [comment]
feel free to contribute @loulou2852
