### ISSUE TITLE
Choosing a code of conduct

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#345]
Hello,

As `our` **community** is growing fast (at least I hope, so :stuck_out_tongue_winking_eye:), it will be useful to choose a code of conduct, at least to be warm to `new comers`

@tbrand @aichholzer @OvermindDL1 any thoughts ?

Regards,

**Comment by OvermindDL1** [comment]
I tend to just go with the Golden Rule, in general just be nice and be logical.  :-)

**Comment by stakach** [comment]
I think the Rubinius code of conduct is pretty good: https://book.rubinius.com/manuscript/code_of_conduct.html

**Comment by aichholzer** [comment]
Something smaller could look like [this](https://github.com/GetRayo/rayo.js/blob/master/CODE_OF_CONDUCT.md).

**Comment by OvermindDL1** [comment]
A couple notes, shorter is definitely better, even the shorter one that @aichholzer linked is still too long (so much so that no one will read it).  Also why do both of those have such limiting text like `As such, we are committed to providing a friendly, safe and welcoming environment for all, regardless of gender, sexual orientation, ability, ethnicity, socioeconomic status, religion, or non-religion.` in some form of another, that sounds like they exclude potentially any other things.  Why do they not just say something of the form like `As such, we are committed to providing a friendly, safe, and welcoming environment for all, regardless of any attributes there-of.` or so?  Better yet, most of the entire multi-paragraphs that both contain could really just be summed up as `Be nice.`, so I still lean back to my original version of `Be nice and be logical.`.  It is easily quoteable, can be plastered around everywhere, and doesn't need a monolithic file that no one will read and that seems to just exist for the purposes of being self-serving rather than actually useful.  :-)

**Comment by stakach** [comment]
I do feel there should be some kind of accountability clause though. Some thing to give "be nice" teeth - just so people are aware of the possible consequences of their behaviour.

Possibly `Be nice and be logical or risk the removal of your project and/or a ban from further involvement in the community.`

**Comment by OvermindDL1** [comment]
Eh, except it's a Code Of Conduct, not Rules, just a Code, and for a Code that sounds very hostile, which I don't think is a great impression to give?  >.>

Plus that cost seems pretty usual as that is what happens about anywhere.

**Comment by stakach** [comment]
@OvermindDL1 that’s kind of the point
https://mor10.com/why-codes-of-conduct-matter/

**Comment by OvermindDL1** [comment]
That article seems quite biased, but I think I live in more of the second set rather than the first, that the rules are obvious because of standard human interactions and since they can be enforced then they should and will, and that the CoC is more of a reminder of how to act.  Trying to make a CoC too long, complex, or filled with examples makes it lose it's entire meaning instead of being to the point and logical instead of emotional.  Hence my usual goto of `Be Nice and Be Logical`, the Nice part is referencing human interactions and the Logical part is referencing staying on topic and being productive.  The CoC's I've been seeing so far seem to just be focusing on the human interaction element and in a very limited way when it should absolutely be more all-encompassing.

**Comment by OvermindDL1** [comment]
Even note in the article you linked, both 'examples' are easily covered by the 'Nice' clause.  And yet the article doesn't mention remaining on topic or being productive whatsoever, my 'Logical' part.

That article, near in full, seems to be a classic case of multiple logical fallacies, including but not limited to Ad Hominem for assuming how someone would react in a situation instead of dealing with it properly (covered under both Nice and Logical), quite a large amount of Straw Man, again for assuming how people will act in a given situation instead of assuming better of humanity to keep the less good aspects down (the less good aspects are generally undeterred by CoC's as that is in general the Troll culture, removing their power by removing your effects to it (Nice) and staying on topic instead of following their lead (Logical) has done very well in every community I frequent), Appeal to Ignorance due to assuming people don't know or know how to react to trolling, False Dichotomy as having a CoC or not is not the only options but rather there is a whole range of actions, Slippery Slope by assuming that not having a CoC means a lead to Chaos (what on earth?!), Circular Argument by saying that a CoC is the only way that enforcement happens and that enforcement happens by CoC, Hasty Generalizations (I'm just listing now because I keep going over the article for each one and wow it seems to have them so many...), Red Herring, Appeal to Emotion (this whole thing seems to be an appeal to emotion, it doesn't even seem to try to hide it, again, Be Logical), Causal Fallacy (this one I should also point out due to how widespread it is in the article), Appeal to Authority, Equivocation (so much of this!), Appeal to Pity, and so many more that I'm giving up now...

That article is a perfect example of Logical Fallacy Death and I have to question those that would fall for it...  Unbiased Research is what should remain paramount.  If a CoC is going to be used then it needs to be all encompassing and easily quotable, the ones listed prior are absolutely not and seem to be nothing but a power trip.

**Comment by stakach** [comment]
I hear you @OvermindDL1 and totally agree that "be nice" is the solution for people everywhere.

But what do you loose by adding a document that you never have to even read that will make a bunch of people feel safe to contribute and comment?

It's not being added for the benefit of anyone involved in this conversation, probably not for most people involved in this project. Basically it does no harm and potentially makes someone feel included.

**Comment by stakach** [comment]
So you disagree with what say https://book.rubinius.com/manuscript/code_of_conduct.html says?
If not then why not include it?
I don’t want to make it a binary issue (if you’re not with us then you’re against us) as I’m sure your hearts in the right place. But outside of “people should just know” what do you have against it, does it hurt you personally to know such a document is sitting in the repo?

**Comment by stakach** [comment]
I don’t personally know anyone either but I’ve seen a few conflicts play out in various projects. Rubinius being one of them - and the reason they have a code of conduct.
Libuv was a more recent one

https://www.reddit.com/r/KotakuInAction/comments/2thi8n/the_time_sjws_harassed_ben_noordhuis_out_of/

In any case I’m not saying it’s a silver bullet and really I’m not at all fussed either way if community standards are up held.
Just don’t think it hurts anyone to outline what is desirable and acceptable

**Comment by OvermindDL1** [comment]
My issue is that it is not entirely encompassing.  All the ones linked so far, including that rubinius link, seem to focus primarily on certain things, here's an excerpt from that rubinius link:

> As such, we are committed to providing a friendly, safe and welcoming environment for all, regardless of gender, sexual orientation, ability, ethnicity, socioeconomic status, religion, or non-religion.

Why are these pointed out at all?  Is it secretly trying to pick on certain people?  Is it trying to pick on 'these' people by being sarcastic?  Why is it not including of every attribute, what is special about these?  What on earth do things like gender or sexual orientation or ethnicity or such things have to do with programming?!  Even mentioning such things at all sounds like there is a non-programming-related agenda, which does *not* belong in a programming project, only code matters and being Nice in how you interact with it.  I have nothing against those being included, just 'why' those and not any other attributes?  Why is the word `regardless` being used as in this context that implies derogatory affiliations with the list that follows, which is one of the big *big* things that is rubbing me wrong (there is *NOTHING* wrong with anything about gender, sexual orientation, ability, ethnicity, socioeconomic status, etc... *ESPECIALLY* when it comes to programming ability, so why are these being brought up at all?!).

**Comment by OvermindDL1** [comment]
@stakach Uh, wtf.... o.O

That is, uh... quite an interesting URL you posted there, I seem to be out of the loop...  Can some questions be answered about that URL's contents?

Who is 'Ben Noordhuis', I'm guessing a dev in libuv and nodejs, but why was he harassed?

What are SJW's?  New name for online 'trolls' or something?  'Troll' seems descriptive enough to me and it's been in use since the old BBS era 35-40 years ago that I've been on such systems...

> No, there's no need for this pull request be it requested from a man or woman. That's the whole issue I have. This PR will not advance women in tech, it will not increase the awareness, it will not get more women in tech or STEM majors. Such a trivial and minor change is about-face and grandstanding. You really want to make a change? Go volunteer at your local high school and get girls excited about tech or other STEM fields. Support groups like PyLadies or Women Who Code, CodeChix who are trying to bring in and support women into the field. But this PR? This PR is political: to be able to say "I stand for women's right in tech" because you changed a gendered pronoun without actual consequence.

Uh, what does gender have to do with coding abilities?  I work at a college in near the center of the united states, the female<->male ratio easily has female's outnumber the males at least 2 to 1 for students and I'm one of only a few dozen males out of *hundreds* of female employees (including all the top bosses), and if anyone started bringing up gendered-specific *anything*, whether male or female, they'd be near fired instantly.  The only thing of such attributes that rubinius listed that is even allowed to be talked about here is socioeconomic status and such related factors as we try to get as much assistance to such students as possible.

> but they came across a single instance of "he" in the documentation, in a short sentence about an error code return.

That's entirely reasonable and taught here as proper English form as English does not have a gender-less singular word thus the simpliest word (shortest in this context) becomes the default, it is a popular pattern in many languages, not just English.  The gender-less plural word `they` and such similar forms can used if singular is not required in the context.  So this is more trolling by the trolls I guess?  Doesn't anyone remember the old phrase `"Don't Feed The Trolls"`...  >.>

> carried a weight of threat - as if "sure, you've made a small mistake, but don't correct this and it's nuclear"
> an arrogance do to the fact that the stats of these requests will go into someone's profile, perhaps the first and finale "contribution" they would make to this project but be labeled as a "contributor".

This seems fairly common, just a simple spelling fix will not get merged via gethub but rather via a diff merge, spelling corrections generally won't get you the 'Contributor' tag on may github projects because of that.

> and assertions that the author is sexist

(This section was updated later to make sure I didn't come across anything that changed the thought)
I'm not seeing where the PR appeared sexist at all, and that is a *BIG* word to throw around.  At my job just mentioning that word launches a full scale investigation that *will* tear things apart, that hasn't happened in near 2 decades now though.

> But while Isaac is a Joyent employee, Ben is not—and if he had been, he wouldn't be as of this morning: to reject a pull request that eliminates a gendered pronoun on the principle that pronouns should in fact be gendered would constitute a fireable offense for me and for Joyent. On the one hand, it seems ridiculous (absurd, perhaps) to fire someone over a pronoun -- but to characterize it that way would be a gross oversimplification: it's not the use of the gendered pronoun that's at issue (that's just sloppy), but rather the insistence that pronouns should in fact be gendered.

Uh, wtf here too...  English doesn't even *have* genderless pronouns, yes English is a crappy language (I prefer lojban personally), and yes I'd prefer if it had genderless pronouns, but it is decently (if horribly) defined, that is what allows everyone to communicate and understand each other...  >.>

I shudder to think what these Trolls go on about in French and such languages where every-single-noun is gendered, it's an aspect of many Latin based languages (interesting not latin itself I think?), and yes Latin-based languages do indeed suck (let's all speak lojban!  ^.^).

---

Aaaand *oy*, the rest of that thread is horrible, this is like the ultimate form of Feeding The Trolls...

### Don't Feed The Trolls!

That phrase has been around for at *least* 30 if not 40 years...  >.>

**Comment by OvermindDL1** [comment]
Still no clue what that has to do with a CoC though, nothing about the PR listed seemed to have an issue with *any* of the listed attributes of the person (as it shouldn't, a person's attributes don't matter in programming contexts, only their code output does).

**Comment by OvermindDL1** [comment]
Do you'll frequent an IRC channel yet or so?  Real-time would be so much more productive...  ^.^

**Comment by stakach** [comment]
Nothing public... Also it's 1am on a Sat morning here (Australia) after an end of week bender, so about to hit the sack.
I'm in New York next week though - so no idea where you live but always up for a lively debate over a brew :)

**Comment by aichholzer** [comment]
Quite the debate going on here...
Let's wrap it up. I will take the lead here; we stick with the "standard" (for lack of a better word) and include a `CoC` in the next release. Thank you gentlemen.
