### ISSUE TITLE
Spring-framework is broken

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3506]
Hi @lukaszlenart,

Updating results, I found that `spring-framework` is broken.

I've attached error log in https://gist.github.com/waghanza/b2e715326c0499f001829e27b72cda77

Any idea ?

Regards,

**Comment by lukaszlenart** [comment]
This is strange, also it reports duplication based on the same jar, I have no idea why. I will try test it locally.

**Comment by lukaszlenart** [comment]
Or maybe I will change this to use Embedded Jetty instead of Jetty Runner (which is deprecated) as I did for [Struts)(https://github.com/the-benchmarker/web-frameworks/pull/3112)?

Also why all the artifacts are named [benchmark](https://github.com/the-benchmarker/web-frameworks/blob/master/java/struts2/pom.xml#L9)?

**Comment by waghanza** [comment]
> This is strange, also it reports duplication based on the same jar, I have no idea why. I will try test it locally.

Seems there is a conflict, as I understand, in dependencies

> Or maybe I will change this to use Embedded Jetty instead of Jetty Runner

It will be awesome, as you may know I have no java skills

> Also why all the artifacts are named benchmark

To have a standard name ... could be named `server` btw
