### ISSUE TITLE
Clarify readme

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3639]
There is an open discussion made on https://github.com/the-benchmarker/web-frameworks/discussions/3641#discussion-81919 to collect everyone's idea / clarify `README`

---------
Any feedback is welcome @the-benchmarker/web-frameworks ❤️

**Comment by System-Glitch** [comment]
A definition of framework in that case would be that it has more than one purpose. For example, gorilla/mux is not a framework because its only purpose is routing, therefore, it is a library.

My own definition differs but I don't think there is any real consensus over the exact meaning of "framework". In my opinion, a framework is necessarily opinionated, because of the etymology of the word "framework".

**Comment by dominikzogg** [comment]
@waghanza i like the categories
chubbyphp for example would be micro, non opiniated

@System-Glitch my opinion is the following:
framework => calls your code
library => get called by your code

Router itself can be a library, the code code calling the controller/action what ever would be a framework by that definition.

**Comment by waghanza** [comment]
> Edit: This conversation would be suited for the new Github Conversation feature.

👍 feel free to open one

**Comment by System-Glitch** [comment]
> > Edit: This conversation would be suited for the new Github Conversation feature.
> 
> +1 feel free to open one

You need to enable Conversation in the repository settings first.

**Comment by waghanza** [comment]
> > > Edit: This conversation would be suited for the new Github Conversation feature.
> > 
> > 
> > +1 feel free to open one
> 
> You need to enable Discussions in the repository settings first.

I opened https://github.com/the-benchmarker/web-frameworks/discussions/3641#discussion-81919 @System-Glitch
