### ISSUE TITLE
There is no such thing as JavaScript version 14.15!

### ISSUE THREAD

**Issue by danielcasler** [the-benchmarker/web-frameworks#3767]
I reported this before but nothing was done about it.

**There is no such thing as JavaScript version 14.15.** You are using a RUNTIME, which is Node.js. The Node.js runtime version is 14.15. A correct version of JavaScript would be ECMAScript 2019 (ES2019). You can find all versions of ECMAScript here: https://en.wikipedia.org/wiki/ECMAScript  

The way your benchmark displays the language as JavaScript version 14.5 is deceptive and misleading. _How do you expect professional engineers to take your benchmarks seriously when you can't get this right?_

I hope you will do the right thing and ensure the data you present is accurate and factual going forward.

**Comment by waghanza** [comment]
Hi @danielcasler,

Indeed, `javascript` is not a common language -> I mean the runtime is not at the same version.

This will be clarified. Next step is to introduce `flavors` (either various runtimes or compilations options) so as the this project could be aware of the underlying runtime (which is `node` actually).

Thanks for reminder.

Regards,

PS : I'll close this issue since I will work on `flavors` somewhere around the week end
