### ISSUE TITLE
Composer install without lock file

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3788]
Since we have no `lock` files, `composer` complains
```
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
```

See https://github.com/the-benchmarker/web-frameworks/pull/3786/checks?check_run_id=1713645781#step:6:1218

What does it mean ?

/cc @sy-records @leocavalcante

**Comment by leocavalcante** [comment]
Dependencies won't be locked, if `composer.json` requires `v1.0`, but there is a `v1.1` available, it will download the `v1.1` like `Gemfile.lock`.
Usually a `composer.lock` is the best option because despite things like SemVer, minor version upgrades can introduce bugs, security vulnerabilities, maybe even API breaks.
Also, with locked dependencies, the dependency resolution isn't necessary and the `install` command can skip this step and run faster.

**Comment by waghanza** [comment]
So no need to worry about that @leocavalcante ?

**Comment by sy-records** [comment]
yes, can ignore it.
