### ISSUE TITLE
Add µWebSockets.js to benchmark

### ISSUE THREAD

**Issue by leandroluk** [the-benchmarker/web-frameworks#3988]
Hi, plz take look in this soluction for JS Api's: https://github.com/uNetworking/uWebSockets.js

**Comment by waghanza** [comment]
Hello @leandroluk,

Thanks for your proposal. The author of the above project do not want `uWebSocket` to be included in here
@see https://github.com/the-benchmarker/web-frameworks/issues/1064#issuecomment-516319796

Having explicit consent, or no opposition, is a requirement to be in here, so we can not include `uWebSocket` for now.

Regards,

PS : Some frameworks in here use it anyway

**Comment by uNetworkingAB** [comment]
It's not about "safe space consent" - the issue is that your results are (as thoroughly proven in that series of comments, linked) extremely chaotic, inconsistent and self contradictory. Your own data concludes one round that X is way bigger than Y, then another round that X = Y then another round that X is less than X.

None of this is reliable science. It's amateurish gobble gabble and I do not want to have anything to do with illogical, chaotic, nonsense.

Go back to school and get basic science correct, is what I'm saying. This is not about "consent". One report cannot fundamentally contradict your first report unless one of your reports or both are entirely, fundamentally, wrong. And I simply do not respect people who are incompetent morons

**Comment by waghanza** [comment]
Thanks for your nice comments @uNetworkingAB.

I'm aware that, at this stage, results are not what is expected / what happens in real life. The reason is only that we are still not in (what I like to say) **production-ready** (results are computed from local dockers mainly).

Thus, the methodology used here is the same that in techempower (for example). 

The idea is not the to say if the results are useful or not, the question is more about your wish (as `uWebSocket` author). If your are interesting of being here, you can, if you are not, we are not forcing.

**Comment by uNetworkingAB** [comment]
The results are, not just worthless, they are misleading fake pseudo science and whenever someone points that out, by using the most basic logic, you hide behind this explanation that **"oh yeah I actually know my results are entirely wrong and misleading"**, but lacking in character to the wild degree of preferring to spread false, nonsensical and misleading information under ones name, for several years, instead of just admitting your reporting doesn't even logically make sense. A 5-year old could deduct that such logic does not make sense and is, thoroughly ridiculous.
