### ISSUE TITLE
Update aspnet core

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#402]
Hi @petersonfs @glennc @Eilon,

**ASP** implementation is here in `1.1`.

Do you mind helping us porting to `2.1` ?

Regards,

**Comment by Eilon** [comment]
Taking a look...

**Comment by waghanza** [comment]
Awesome

**Comment by waghanza** [comment]
Thanks for your contributions @Eilon @sebastienros

**Comment by waghanza** [comment]
@Eilon @sebastienros as I understand `ASP.NET core` use `C#` **7.3** ?

I want to specify version on `README`

**Comment by sebastienros** [comment]
The language version is irrelevant here. And I don't even know which one it's using as the project doesn't specify it so it's using whatever default the sdk decides it is. What is important is the dotnet runtime version, which is 2.1.

**Comment by waghanza** [comment]
@sebastienros I disgree

As considering only `C#`, or any language that needs a **build** step, I can agree with you (for this perspective)

However, this project tends to be larger (having dynamic language) and then the information about language version is useful.

For example, comparing `ruby` `2.5` and `php` `5` **IS** irrelevant, and having information about language version is interesting in this perspective

**Comment by Eilon** [comment]
@sebastienros - can we just set the lang version explicitly in the csproj?

@waghanza in the case of .NET the language is completely separate from the runtime, which is not exactly true in practice in other systems. You can use C# 7.3 with .NET 2.0, 2.1, 2.2, etc. and get different runtime performance because of the runtime improvements/changes.
