### ISSUE TITLE
How is it different than TechEmpower

### ISSUE THREAD

**Issue by sebastienros** [the-benchmarker/web-frameworks#409]
TechEmpower provides more scenarios, including database and json ones.

https://github.com/TechEmpower/FrameworkBenchmarks

**Comment by waghanza** [comment]
sure @sebastienros **tfb** is more complete, however the goal are different here. 

we want to compare performance of each framework (**full stack**, **micro** ...) but keeping implementations / scenarios simple. 

To clarify, I'll say that **tfb** is more complete, but also more complex to understand results (it require some technical knowledge to understand results).

As a example, I'll say that some **frameworks** are used, `here` and in `tfb`, but somes are used of **tfb** only and the purpose if not to have them here. For example, embedding some `ruby` **scripts** in a [h2o](http://h2o.examp1e.net) is not our purpose `here`.

**Comment by doanguyen** [comment]
Hi,

don't you mind if i reopen the issue? I would think we should focus on the framework that has a reasonable number of user base. Like >1k stars on Github or whatsoever.

What do you think?

**Comment by waghanza** [comment]
Hi @doanguyen,

Feel free to enjoy our work :heart: 

Ideas are welcome

For me the main idea behind this project is to compare **framework**, but in order to avoid a messy project, it seems accurate to have some conditions to validate candidates. 

In my point of view, candidates **SHOULD** be accepted only with a **feature** basis. I mean that to ensure a minimum of innovation / real-word usage, **framework** presented here **SHOULD** :
+ have `routing` feature
+ be stable
   + on [pypi](http://pypi.org) for `python`, [rubygem](http://rubygems.org), ...
   + in version <= 1
+ native,  for example **NOT** [turbo](http://npmjs.com/package/turbo-http) in `node`
+ implemented in language (no [cython](http://cython.org), no [ph7](http://ph7.symisc.net), no [jruby](http://jruby.org) ...)

What do you think ?

**Comment by doanguyen** [comment]
:heart: 

* routing feature seems obvious since it's framework, not a library. So isn't it in the title already?
* Idk. versioning is a mess, so up to you. (but i think vibora, sanic,... is unqualified)
* Why do you hate those languages :)) 

anyway, at the end of the day I think it's just the question of how many people are doing this/that framework, no matter what language is this.

**Comment by waghanza** [comment]
PS : I do not hate any languages, languages are **tools** not **goals** (**goals** could be hated, not **tools** used to get to it)

:+1: 

vibora and sanic has **NOT** to be show by default -> adding **experimental** `flag`

What I mean with no jruby ... is that by default implementations in `ruby` (for example) **SHOULD** use standard `ruby`, or we can even consider creating a **foler** for `jruby` but not mixing ruby and jruby, and ironruby ;-)

**Comment by doanguyen** [comment]
Yep, I agree we use only the most widely interpreter of these languages unless someone needs it really hard.
