### ISSUE TITLE
Add atom (when it will be ready)

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#418]
+ Language : crystal
+ Repo : https://github.com/atomframework/atom
+ Author : @vladfaust

**Comment by vladfaust** [comment]
Invitation accepted, thanks, @waghanza!

**Comment by waghanza** [comment]
@vladfaust any plan for `atom` ? I'm very impatient

**Comment by vladfaust** [comment]
There are big plans for Atom Framework, @waghanza. I'm working on it. 

It's like 70% ready, I need to wrap it up better with docs and to create the website.

I want Atom to be a beautiful and simple product for a newcomer, when they can just set and go without needing to learn too much about low-level Crystal stuff. However, an app created with Atom must be extensible (i.e. open for low-level changes) and able to grow with a developer's knowledge of Crystal, as well as their business needs. That's the mission of Atom Framework and there is a plenty of engineering and design challenges, that's why it's taking so much time. 

Nevertheless, I'm pretty sure it's going to be live before X-Mas! ✅
