### ISSUE TITLE
[PHP] Add octane package to Laravel

### ISSUE THREAD

**Issue by potros** [the-benchmarker/web-frameworks#4247]
Please add octane package to Laravel so it will make it compare better with other frameworks
https://github.com/laravel/octane

**Comment by waghanza** [comment]
Hi @potros,

Be my guest, will be a great addition.

BTW, it is planned to have this.

`laravel` is already listed with **swoole** in here => https://github.com/the-benchmarker/web-frameworks/tree/master/php/laravel-s-laravel

Regards,

**Comment by waghanza** [comment]
btw, we can not add `PHP` frameworks anymore until https://github.com/the-benchmarker/web-frameworks/pull/3958 get ready

**Comment by potros** [comment]
> `laravel` is already listed with **swoole** in here => https://github.com/the-benchmarker/web-frameworks/tree/master/php/laravel-s-laravel

Yes, but octane is maintained by the laravel team itself so it will be more optimized

Regards,

**Comment by waghanza** [comment]
> Yes, but octane is maintained by the laravel team itself so it will be more optimized

Yeah, it is a `laravel` product. I'm not quite sure we can say that more optimized because handled by same team.

Btw,
- I though it is more **production-grade** (yet) https://github.com/hhxsv5/laravel-s/issues/351#issuecomment-825446566
- Glad to add it when ready (or to review any PR)
- We can not add any PHP until https://github.com/the-benchmarker/web-frameworks/pull/3958 (CI could not handled it)

**Comment by potros** [comment]
yes you are right we will need to wait for octane to reach 1.0
and of course #3958

Regards,
