### ISSUE TITLE
Display RAM usage

### ISSUE THREAD

**Issue by Wdestroier** [the-benchmarker/web-frameworks#4832]
Is it possible to add the max RAM memory usage to the benchmark?

May not be a trivial task, because a framework can split the work across many processes...

**Comment by waghanza** [comment]
Hi @Wdestroier,

Indeed this is not trivial. We plan to do this, but in a very very long roadmap.

Let me add more context to that. The main idea is to compute any resource consumption while running on cloud (since resources consumed, as you noticed, could be split into multiple, pods, vms, core ...).

This feature is a, for me, a subtask of `Run on cloud` in https://github.com/the-benchmarker/web-frameworks/issues/3108

Regards,

**Comment by Wdestroier** [comment]
Thanks, Marwan! 😄

I will be closing this issue, because it's already covered in the road map.
