### ISSUE TITLE
Measure concurrency levels

### ISSUE THREAD

**Issue by dalu** [the-benchmarker/web-frameworks#487]
+ Language : any

Currently you're measuring latency and requests/second. That nice eyecandy but it says nothing about the robustness of the used tech.

I suggest you also meansure concurrency values.

start with 50, 200, 1000, 2000, 5000, 10000.

Let's see when those "blazing fast, high request processing" frameworks start returning errors.

**Comment by waghanza** [comment]
Hi @dalu,

The `concurrency` level is **fixed** for now -> e.g : `wrk` use `1000` requests per thread 
https://github.com/the-benchmarker/web-frameworks/blob/master/tools/src/benchmarker.cr#L12-L13
but it could be changed, using command line switches

This idea is great, but this **feature** has to be explained by a  `real-word` use case :stuck_out_tongue: 

I mean, why not ? but :
+ not a priority
+ this feature has to be explained (what **real-world** usage ...)

**Comment by OvermindDL1** [comment]
> Let's see when those "blazing fast, high request processing" frameworks start returning errors.

That's something I keep saying needs to be measured.  ^.^

Concurrency is important because it relates to how many connections it can handle before they fail (say with a long database request each or something).

You could emulate it be just `sleep(1s)` as a simple test if you want to add a new route, perhaps `/sleep/:time` where the integral value is the number of milliseconds or seconds or so to sleep for and it must not return before that time has elapsed or it fails and it would allow the test to gradually increase it longer and longer to test each framework and how they handle concurrency (even single-threaded servers will handle this excellently if they are made well).

**Comment by dalu** [comment]
Real world use is at hand.

If you need 100 servers to handle the same amount of visitors (e.g. 50 concurrent, e.g. php 5.6 symfony 2) what 1 server could handle (e.g. 5000 concurrent Go stdlib) then there's your real world usage. Unless I misunderstood the term. Because hitting helloworld repeatedly, what you're doing now, isn't much different.

I mean that's for starters. Then you'd have 3 metrics. Latency, requests/second and concurrency.
I'm 100% sure those requests/second and latency values will change dramatically when you turn up the amount of concurrent requests with wrk.

Personally I don't think... well yes database could be simulated with sleep(), that would also be an interesting option (what OvermindDL wrote). To finish the sentence, I don't think real databases should be used because that would add more variables and wouldn't measure the http server side of things only.

Display?

Since concurrency is now at 1000, add 2000 and 5000.

5000 is usually the magic number any dedicated and traditional web server like apache or nginx  can handle before errors start appearing. A concurrency level of 1000 doesn't really say much at all.

Don't forget to adjust open file limits (`/etc/security/limits.conf`, or if using systemd there are separate settings in the service definition), usually open file limit is at 1024.

So display results with each concurrency setting, not a big deal really.

**Comment by waghanza** [comment]
I understand all advices here, but the big deal is : how to display this whitout going in a mess ?

**Comment by OvermindDL1** [comment]
> I understand all advices here, but the big deal is : how to display this whitout going in a mess ?

Just another sorted table I'd say.

**Comment by waghanza** [comment]
i think it is counter-productive. I suggest :
+ Leaving result tables as-is for now
+ Gather ideas about what metrics are useful
+ Create a roadmap / priority list to show that we are working on

What do you think ?

**Comment by dalu** [comment]
example

# 1000 concurrent

table latency

table requests / second

# 2000 concurrent

table latency

table requests / second

# 5000 concurrent

table latency

table requests / second

**Comment by dalu** [comment]
1000 visitors at the same time

2000 visitors at the same time

5000 visitors at the same time

I'm not sure if your goal even is finding truth but selling your favorite framework tbh

**Comment by waghanza** [comment]
@dalu it's not a question of choosing your favorite framework, but showing what frameworks can do in **real-world** usage :stuck_out_tongue:

**Comment by waghanza** [comment]
To clarify my thoughts, I would say that in **real-world**, you usually have some load balancers before your frontend servers, then making an equality with visitors is for me not a good approach

I tend to correlate 3 types of datas :

+ hardware resources (servers ...)
+ human resources (which language know or **could** know your team)
+ customers resources (how many people do you reach with your service)

**Comment by OvermindDL1** [comment]
> To clarify my thoughts, I would say that in real-world, you usually have some load balancers before your frontend servers, then making an equality with visitors is for me not a good approach

I've never had load balancers in front and I've handled traffic with literally millions of requests per day with ~40k *concurrent* connections averaging >350 terabytes transfer a month for years at a time.  The BEAM handles that without needing load balancers (it is self-balancing), back-end data replication like Redis (also built-in to the BEAM via it's node and message distribution system), no downtime on updates (the BEAM VM supports hot-code loading so you can update on the fly without ever taking something down), etc... etc...  There's a reason the BEAM is used by a lot of *large* companies and is used by more people than you'd expect (look at CouchDB for example, the distributed document storage database, built on the BEAM in Erlang as a super-common self-hosted example), yet none of the tests here really test it's power, such as the BEAM is designed to just Not Fail, even in the case of catestrophic hardware failure (automatic migration to other nodes/servers), massive load (40k concurrent connections was not even scratching my server), etc... etc...

**Comment by waghanza** [comment]
@ OvermindDL1 BEAM is not a load balancer itself ?

Sorry, if I mislead someone, I am too sticky with my dynamic languages.

As for example ruby, you usually run with `puma` (or else) what load balance between all hardware resources.

We also use generaly nginx, haproxy, AWS alb to load balance (and also fail over) customer traffic

**Comment by OvermindDL1** [comment]
> As for example ruby, you usually run with puma (or else) what load balance between all hardware resources.

Indeed, but things like this are entirely unnecessary with the BEAM VM.  There is an old Meme in the Erlang/Elixir-world that lists all the different software that a general high-output Ruby web server requires and the entire BEAM column just lists the BEAM, wish I could find it...  ^.^;

In reality the Postgres web server is often used with the BEAM, the built-in mnesia is a good distributed KV database, but it's no relational database.  ^.^

> Sorry, if I mislead someone, I am too sticky with my dynamic languages.

The BEAM and almost all languages on top of it are also dynamic though?  (The alpaca language on it is statically typed however, but it does still compile down to the untyped BEAM instructions).

> We also use generaly nginx, haproxy, AWS alb to load balance (and also fail over) customer traffic

With most BEAM setups you just setup your DNS properly, setup your beam nodes, mesh network them together (a single call), and unless something stupid is done like funneling all access through a single actor instead of using one of the built-in pools and distribution methods then it will just and balance as expected (and there are libraries that can even delegate work to lesser loaded nodes or hidden nodes, there are libraries to do about anything in regards to multi-server handling on the beam considering how simple it is to set up).

**Comment by waghanza** [comment]
Sure, what I try to say is that on **real-world*" we can choose BEAM (for what purpose elixir is for) but for ruby we use load balancers

A equality could be done here
BEAM = ruby + puma + nginx (simplication made on purpose)

But this is quite far away that the initial idea 😁

**Comment by waghanza** [comment]
When you speak about postgres webserver, could you be more precise, I didn't know PG has a webserver inside 🤣

**Comment by OvermindDL1** [comment]
> When you speak about postgres webserver, could you be more precise, I didn't know PG has a webserver inside rofl

> In reality the Postgres web server is often used with the BEAM, the built-in mnesia is a good distributed KV database, but it's no relational database. ^.^

Meaning that PostgreSQL is often used 'as the main database' with most Elixir web servers, since it (as of versions the past few years) can be distributed, supports relational data, supports KV data, supports document store, built-in support for a lot of things like positional data, streaming query changes in realtime, pub/sub (not really that used with Elixir apps since it has a better pub/sub system included), and a whole ton more.  The built-in database to Elixir, MNesia, is a Key/Value store so not as generically useful (it's primarily used as a settings and state storage).

As an aside though, there are PGSQL plugins for web serving the data, though I've never used such things.  ^.^;

**Comment by OvermindDL1** [comment]
> There is also http://postgrest.org :joy:

Lol, that's hilarious, and looks so wonderfully inefficient.  ^.^

**Comment by waghanza** [comment]
Why?

**Comment by OvermindDL1** [comment]
> Why?

RESTful API's are not terribly efficient since they tend to perform single table queries, something like GraphQL's style is significantly more efficient as it can build better optimized queries to get all needed data in a single request.  Plus you lose capabilities like on-update streaming and so forth.

**Comment by waghanza** [comment]
Ah, I think you mix REST design ans RESTful API.

For example, HATEOS is one implementation of REST design, but tends to be several tables querying (something like graphql, but without having yo write query client side)

**Comment by OvermindDL1** [comment]
Not mixed up, RESTful API's are very static.  If you only need a single field that is the result of merging two things then you either have to hope they have a dedicated endpoint *just* for that or you have to potentially do multiple queries and get lots and lots of data that you don't care about back, where with GraphQL you construct precisely what you need and that's all you get back, which is a monstrous **boon** in network traffic and speed both especially on things like limited mobile networks.

**Comment by waghanza** [comment]
Look at https://jsonapi.org😊

**Comment by OvermindDL1** [comment]
> Look at https://jsonapi.org

What about it?  It's just a method of formatting a json output, doesn't do anything to reduce round-trips or request a specific element from something that usually gives more or anything of the sort?

**Comment by waghanza** [comment]
nop, you can retrieve several resources at once, select fields you want ...
avoid doing :
+ 1 call = 1 resource
+ always get all fields (no filtering before network)

**Comment by proyb6** [comment]
I’m not sure if having 5 sec runs for each framework is useful, particularly Jester (Nim) seems to have lower/worse throughput when running at short duration as 5s or 10s with wrk but normal a time long duration.

**Comment by waghanza** [comment]
@proyb6 5 sec ?

**Comment by waghanza** [comment]
the tool run with a 15s duration test (changeable with a command line option)
https://github.com/the-benchmarker/web-frameworks/blob/master/tools/src/client.cr#L11

**Comment by proyb6** [comment]
I see, it's better with pipelines benchmark.
