### ISSUE TITLE
OpenLiteSpeed as an alternative to Nginx

### ISSUE THREAD

**Issue by jamesli2021** [the-benchmarker/web-frameworks#5497]
LiteSpeed Enterprise is widespread across web hosting that could be interesting when OpenLifeSpeed (non-enterprise) is use in the benchmark comparison.

**Comment by waghanza** [comment]
Hi @jamesli2021,

Thanks for the idea. Not sure this matter in fact ...

Let me explain. We are benchmarking web frameworks.

The compiled / java-based languages has built-in servers (`go`, `kotlin` ...).

`nginx` is used only for some interpreted languages (`ruby`, `python`, ...).

The most important for me, is results consistency. If we want to compare for example `ruby` and `python` (could be legitimate somehow) we should compare only if they are using the same http layer engine, no matter what it is.

I've taken `nginx` since it is really a swiss-knife, but OpenLiteSpeed could have been choosen.

For me this idea could be implemented only after runtime feature https://github.com/the-benchmarker/web-frameworks/pull/3958

This will then allow results to be shown either with nginx or with openlitespeed (we also can use apache or litehtttp or passenger ...).

Regards,
