### ISSUE TITLE
where is node.js ?

### ISSUE THREAD

**Issue by xcesaralejandro** [the-benchmarker/web-frameworks#5747]
Hello,
I have been looking at the list of frameworks but I have not found node.js, why?

**Comment by waghanza** [comment]
Hi @xcesaralejandro,

You mean, that there is no `node.js` implementation in **javascript** ? Like `swoole` for **php**. The reason is that nobody made it 😛 but feel free to do so if you want to participate in this project.

Also, **javascript** folder list plenty of frameworks that are using `node` (other engines will come).

Regards,
