### ISSUE TITLE
Error: chubbyphp-roadrunner

### ISSUE THREAD

**Issue by dominikzogg** [the-benchmarker/web-frameworks#6222]
@waghanza is there a way to get more insights of the issue chubbyphp-roadrunner got while benchmarking? I only see a red dot and some error counts.

**Comment by waghanza** [comment]
You mean those dots ?

![Capture d’écran 2023-03-18 à 14 44 49](https://user-images.githubusercontent.com/1440729/226109886-fbb92a6b-cdc4-4d0e-bd64-383e4f178d26.png)

We didn't provide details about this, since this is too complex to analyse, and could come the infrastructure (local docker). I plan to change this but after using a real word infrastructure (I mean using a real world network).

-----------------------

It comes from

https://github.com/the-benchmarker/website/blob/33dc5f3ddb0a2bab2ce2f02fd38d8739902068c0/src/views/BenchmarkResult.tsx#L65

Those figures are coming from `http errors` computed by **wrk** in
```
wrk -H 'Connection: keep-alive' --connections 512 --threads 8 --duration 15 --timeout 1 --script pipeline_post.lua http://127.0.0.1:3000/user/0
Running 15s test @ http://127.0.0.1:3000/user/0
  8 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     6.82ms    4.10ms  75.19ms   73.49%
    Req/Sec     9.37k     0.98k   24.97k    73.53%
  1119706 requests in 15.10s, 91.83MB read
  Non-2xx or 3xx responses: 1119706
Requests/sec:  74153.63
Transfer/sec:      6.08MB
```

----------------------------------

I will close this, feel free to re-open if any question @dominikzogg

**Comment by dominikzogg** [comment]
@waghanza strange, cannot reproduce it on my notebook. Thanks for helping me anyway.
