### ISSUE TITLE
[PHP] Fomo’s solution

### ISSUE THREAD

**Issue by cyrusmsk** [the-benchmarker/web-frameworks#6693]
This solution looks like a hack. Just hardcoded strings returned instead of normal usage, that is described in the Fomo package documentation with the use of Response class.

Could you check this please?

**Comment by waghanza** [comment]
Which line precisely are you referring to @cyrusmsk ?

cc @amirfaramarzi

**Comment by cyrusmsk** [comment]
I mean these manually written responses:

https://github.com/the-benchmarker/web-frameworks/blob/master/php/fomo/app/Controllers/BenchmarkController.php

however the documentation suggests simple and more general code:
`public function store(Request $request): Response
    {
        // insert data
        return response()->asNoContent();
    }
`

**Comment by amirfaramarzi** [comment]
hi @cyrusmsk 

you are right

But you can use both methods in fomo

If you refer to the class below, you will notice that the code of that class produces the same string at the end as in https://github.com/the-benchmarker/web-frameworks/blob/master/php/fomo/app/Controllers /BenchmarkController.php is there. It doesn't matter if you send your response string manually or generate and send it by any other plugin.

https://github.com/fomo-framework/framework/blob/master/src/Response/Response.php

If you mean that there is fraud in the work, we must say that the difference between sending the response through the class or sending it as a manual code string is very small, and if you also use the response class, FOMO is still the fastest php framework. will be

However, in the next versions of Fomo, the responses are supposed to be cached so that even this small difference disappears.

**Comment by waghanza** [comment]
@amirfaramarzi if you be kind enough to make a small PR to stick to the doc, it will be gladly appreciated ❤️

**Comment by amirfaramarzi** [comment]
@waghanza Unfortunately, I don't have time right now, but I will create it as soon as possible, thanks

**Comment by cyrusmsk** [comment]
Thanks guys.
It is not a fraud, but just seeing manual response looks weird for me)
