### ISSUE TITLE
Remove all the trashy php frameworks

### ISSUE THREAD

**Issue by jackcvr** [the-benchmarker/web-frameworks#7810]
Benchmarks have been flooded with micro PHP frameworks based on Workerman or Swoole. Almost all of these frameworks do nothing beyond routing (typically handled by FastRoute). Some of them have only a single function, or even none.

For example:
- https://github.com/passwalls/mark
- https://github.com/fomo-framework/fomo
- https://github.com/simple-swoole/simps
- https://nano.laylatichy.com/

**Comment by waghanza** [comment]
Hi @jackcvr,

You mean that those framework are only thin wrappers around Swoole or Workerman ?

Maybe.

The idea of this project is to should how it could perform / be written. 

If implementing those frameworks is merely equivalent to write pure PHP, I all about  leaving them here.

At least, because their is no maintainance issue

cc @laylatichy @passwalls  @amirfaramarzi @sy-records

**Comment by laylatichy** [comment]
@jackcvr 

hmmm my nano has a lot of modules for it, email, openapi, auth, orm, aws, stripe

https://nano.laylatichy.com/getting-started/introduction.html

yeah, core handling is based around workerman, because I found that package to be efficient at what it does

**Comment by amirfaramarzi** [comment]
hello @jackcvr @waghanza 

No, it's not just like that, at least in the fomo framework

In fomo, I have tried to use the tcp layer instead of the http layer and I am trying to personalize the protocol.

In addition, in the tcp layer, the requests sent to the framework are placed in the cache memory. In addition, most of the classes, including request and response, have been cached in order to create the best performance.

swoole, workerman, etc. are used to implement concurrency, which do not exist internally in php.

If we want to take these frameworks out of the cycle with this idea, all the frameworks that used concurrency in all languages ​​should be taken out of the cycle.

thanks

**Comment by jackcvr** [comment]
Hi @waghanza 

Have you even checked any sources? Look at the best one: https://github.com/passwalls/mark/tree/master.
It's disappointing that someone can spend just half an hour to create a "framework" like this to mess with the results. And the others aren’t much better.

There can be no claims against authors until clear requirements are established. I understand that it’s challenging to define these requirements and review everything, but with current attitude, your benchmarks will eventually become useless.

**Comment by waghanza** [comment]
Hi @jackcvr,

Thanks for clarifying your point.

I'm not sure how this can be useless (I mean having to kind of frameworks).

The idea of this project is to expose performances, and how code could be written with this or that framework.

I understand your point of view, but ... picking a framework is **NOT** only a matter of performance, but also having a :
- big / growing community
- easy to write 
- production ready
- not resource killer
- ...

with this approach any framework could leave here

actually, we only show performance, but this is not the long term goal ❤️
