### ISSUE TITLE
[D] Wrong version

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#7905]
Tis line is incorrect
https://github.com/the-benchmarker/web-frameworks/blob/1ba5e2aeba99ab47806fa815e26028d73f039554/d/config.yaml#L2

According to changelog https://github.com/ldc-developers/ldc/releases/tag/v1.39.0 this version of compiler use 2.109.

cc @cyrusmsk @trikko 

PS : We want to specify the version of D lang in yaml file, not compiler one (after we can compare ldc vs dmd, but this is not the subject here)

**Comment by cyrusmsk** [comment]
There is a reference D compiler DMD and it's version is 2.109 and LDC (LLVM-based backend) is based on DMD (front-end).
So each LDC usually based on some DMD version. So you can use 2.109 yes

**Comment by waghanza** [comment]
And then when https://github.com/ldc-developers/ldc/releases/tag/v1.40.0-beta1 will be out, and stable, we are going to change to 2.110, right ?

**Comment by cyrusmsk** [comment]
The release of 2.110 was delayed, but it will be possible to say it will be 2.110 yes

**Comment by waghanza** [comment]
I'm tracking D lang changelog, so as to update version accordingly

**Comment by cyrusmsk** [comment]
If you are interested - I can send a PR when the next version will be ready.
I'm not updating it mostly because usually there is almost no change in performance that is based on the compiler version for web-frameworks.
If some projects are getting gains from new versions - web-frameworks probably have some internal bottlenecks that are not affected by newer D versions. So they are showing almost the same level of performance.

So without newer approach for coroutines or more performant eventloop I'm not expecting any changes in D solutions soon.

**Comment by waghanza** [comment]
I understand. Some versions of each language could be no performance gain, but bring something new (security, practices, ...).

Better to stick to latest stable or LTS.

The idea behind this project is to help you decide which technology you can choose for a new project, so it is accurate to show the newest version that you could use in production.

I'm happy with your proposal then
