### ISSUE TITLE
Use erlang hipe (high performance) backend for elixir

### ISSUE THREAD

**Issue by jjl** [the-benchmarker/web-frameworks#89]
There is a significant performance boost when using the hipe backend, but the release isn't configured to use it.

**Comment by OvermindDL1** [comment]
Is there?  HiPE often has a performance hit when doing heavy IO, it generally only gains a boost in math-heavy code.  I'd say have 2 implementations, one with HiPE as the JIT, one with BEAM as the JIT.

**Comment by OvermindDL1** [comment]
@kordeviant See:  https://github.com/tbrand/which_is_the_fastest/issues/101

Basically the current benchmarker will not saturate any decent server whatsoever, even tsung is not the best for such tests, as wrk well outperforms it, so that is what should be used, and you can see how well it does there (see bottom comment for latest).  :-)

**Comment by waghanza** [comment]
@OvermindDL1 if you have time for a `PR`, it will be :heart:

**Comment by waghanza** [comment]
@kordeviant now that benchmarker has been completely rewritten (`wrk` is used in the background) it will be inter sting to use `hipe` for **elixir** 

I'm actually working on a **production** version of results, not running on **local** `docker`

**Comment by OvermindDL1** [comment]
> it will be inter sting to use hipe for elixir

If you do make sure to compile OTP with HiPE too, not just the application, mis-matched backend usage incurs a significant performance hit.

**Comment by waghanza** [comment]
@OvermindDL1 I'll be glad to learn :stuck_out_tongue:
